language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"
env:
  - INST_PACKAGES=numpy
  - INST_PACKAGES=

# install dependencies
install:
  - pip install pytest
  - pip install $INST_PACKAGES
  - pip install .
# run tests
script:
  - ./runtests.sh